import { 
    Main,
    DocumentsIn,
    DocumentsOut,
    Nomenclature,
    Scale,
    Grouping,
    History,
    Transfer,
    Inventory,
    Cheques,
    Notifications,
    PriceTags,
    Reports,
    Cashbox,
    Clients,
    Currency,
    Pos,
    Products,
    Suppliers,
    Workers,
    Settings
} from '../components/Dashboard'

export const routes = [
    {path: '/dashboard', element: <Main />},
    {path: '/documents-in', element: <DocumentsIn />},
    {path: '/nomenclature', element: <Nomenclature />},
    {path: '/history', element: <History />},
    {path: '/documents-out', element: <DocumentsOut />},
    {path: '/scale', element: <Scale />},
    {path: '/grouping', element: <Grouping />},
    {path: '/transfer', element: <Transfer />},
    {path: '/inventory', element: <Inventory />},
    {path: '/cheques', element: <Cheques />},
    {path: '/notifications', element: <Notifications />},
    {path: '/price-tags', element: <PriceTags />},
    {path: '/reports', element: <Reports />},
    {path: '/cashbox', element: <Cashbox />},
    {path: '/clients', element: <Clients />},
    {path: '/currency', element: <Currency />},
    {path: '/pos', element: <Pos />},
    {path: '/products', element: <Products />},
    {path: '/suppliers', element: <Suppliers />},
    {path: '/workers', element: <Workers />},
    {path: '/settings', element: <Settings />},
]